import json
import re

ar = json.load(open('public/locales/ar/translation.json', encoding='utf-8'))

# Common translation patterns
translations = {
    # General UI
    "Actions": "الإجراءات",
    "Add": "إضافة",
    "Add permission": "إضافة صلاحية",
    "Status - Completion Date": "الحالة - تاريخ الإنجاز",
    "(edited)": "(تم التعديل)",
    "/ one-time": "/ لمرة واحدة",
    "22%": "22%",
    "2FA Secret Key": "مفتاح 2FA السري",
    "2FA secret key uses base32 characters (A-Z, 2-7) only": "مفتاح 2FA السري يستخدم أحرف base32 (A-Z, 2-7) فقط",
    "30-Day Consumption": "الاستهلاك في 30 يوم",
    "A system error occurred. Please refresh and try again.": "حدث خطأ في النظام. يرجى التحديث والمحاولة مرة أخرى.",
    "ABCD EFGH IJKL MNOP (base32 - leave empty if 2FA is disabled)": "ABCD EFGH IJKL MNOP (base32 - اترك فارغاً إذا كان 2FA معطلاً)",
    "AI Access": "الوصول للذكاء الاصطناعي",
    "AI Assistant": "المساعد الذكي",
    "AI Assistant Analytics": "تحليلات المساعد الذكي",
    "AI Assistant Settings": "إعدادات المساعد الذكي",
    "AI Token Packages": "باقات توكنز الذكاء الاصطناعي",
    "AI Token Plans": "خطط توكنز الذكاء الاصطناعي",
    "AI free tokens limit updated successfully": "تم تحديث حد التوكنز المجانية للذكاء الاصطناعي بنجاح",
    "Accept": "قبول",
    "Accepted": "مقبول",
    "Access Denied": "تم رفض الوصول",
    "Access Denied: Unknown user role.": "تم رفض الوصول: دور مستخدم غير معروف.",
    "Access Denied: Use Admin Sign In.": "تم رفض الوصول: استخدم تسجيل دخول المشرف.",
    "Access Denied: You do not have administrator privileges.": "تم رفض الوصول: ليس لديك صلاحيات المشرف.",
    "Account": "الحساب",
    "Account Email": "البريد الإلكتروني للحساب",
    "Account Email / ID": "البريد الإلكتروني / المعرف",
    "Account Processing": "معالجة الحساب",
    "Account deleted successfully": "تم حذف الحساب بنجاح",
    "Account name is required": "اسم الحساب مطلوب",
    "Account registered successfully!": "تم تسجيل الحساب بنجاح!",
    "Account updated successfully": "تم تحديث الحساب بنجاح",
    "Accounts to follow": "حسابات للمتابعة",
    "Accounts to unfollow": "حسابات لإلغاء المتابعة",
    "Action": "الإجراء",
    "Action URL": "رابط الإجراء",
    "Action cancelled.": "تم إلغاء الإجراء.",
    "Action confirmed and executed.": "تم تأكيد وتنفيذ الإجراء.",
    "Action failed during execution.": "فشل الإجراء أثناء التنفيذ.",
    "Activate": "تفعيل",
    "Activate Account": "تفعيل الحساب",
    "Activate Employee": "تفعيل الموظف",
    "Activate Package": "تفعيل الباقة",
    "Activate free trial for this plan": "تفعيل النسخة التجريبية لهذه الخطة",
    "Activating...": "جارٍ التفعيل...",
    "Active": "نشط",
    "Active Chat": "محادثة نشطة",
    "Active Status": "الحالة النشطة",
    "Active Subscribers": "المشتركون النشطون",
    "Active recently": "نشط مؤخراً",
    "Activity": "النشاط",
    "Activity Status": "حالة النشاط",
    "Add AI Token Package": "إضافة باقة توكنز ذكاء اصطناعي",
    "Add Account": "إضافة حساب",
    "Add Another Pricing Option": "إضافة خيار تسعير آخر",
    "Add Category": "إضافة تصنيف",
    "Add Feature": "إضافة ميزة",
    "Add Holiday": "إضافة عطلة",
    "Add Industry": "إضافة قطاع",
    "Add Members": "إضافة أعضاء",
    "Add Money Receiving Method": "إضافة طريقة استلام أموال",
    "Add New Admin": "إضافة مشرف جديد",
    "Add New Employee": "إضافة موظف جديد",
    "Add New Feature Group": "إضافة مجموعة ميزات جديدة",
    "Add New Industry": "إضافة قطاع جديد",
    "Add New Qualification": "إضافة مؤهل جديد",
    "Add Option": "إضافة خيار",
    "Add Package": "إضافة باقة",
    "Add Plan": "إضافة خطة",
    "Add Salary Transaction": "إضافة معاملة راتب",
    "Add Task": "إضافة مهمة",
    "Add Transaction": "إضافة معاملة",
    "Add a Comment": "إضافة تعليق",
    "Add a Holiday": "إضافة عطلة",
    "Add a rotation shift": "إضافة وردية متناوبة",
    "Add a short description about this file": "أضف وصفاً مختصراً عن هذا الملف",
    "Add an Attendance": "إضافة حضور",
    "Add an employee attendance": "إضافة حضور موظف",
    "Add an employee salary transaction": "إضافة معاملة راتب موظف",
    "Add another task?": "إضافة مهمة أخرى؟",
    "Add image": "إضافة صورة",
    "Add new Twitter account": "إضافة حساب تويتر جديد",
    "Add new category": "إضافة تصنيف جديد",
    "Add new method": "إضافة طريقة جديدة",
    "Add to Calendar": "إضافة إلى التقويم",
    "Add/Update": "إضافة/تحديث",
    "Adding Salary Transaction...": "جارٍ إضافة معاملة الراتب...",
    "Address": "العنوان",
    "Adherence to Deadlines": "الالتزام بالمواعيد النهائية",
    "Admin": "المشرف",
    "Admin accounts are not limited by token balance.": "حسابات المشرفين غير محدودة برصيد التوكنز.",
    "Advance By": "مقدماً بـ",
    "Advance Salary By": "السلفة بـ",
    "Advance salary by value is required": "قيمة السلفة مطلوبة",
    "Alerts": "التنبيهات",
    "All Charts": "جميع الرسوم البيانية",
    "All Industries": "جميع القطاعات",
    "All Projects": "جميع المشاريع",
    "All Sections": "جميع الأقسام",
    "All Statuses": "جميع الحالات",
    "All Templates": "جميع القوالب",
    "All money receiving methods": "جميع طرق استلام الأموال",
    "All tasks": "جميع المهام",
    "Allow creating group chat for the team": "السماح بإنشاء محادثة جماعية للفريق",
    "Allow multiple choice": "السماح باختيار متعدد",
    "Allowed": "مسموح",
    "Already have an account?": "هل لديك حساب بالفعل؟",
    "Amount (Tokens)": "المبلغ (توكنز)",
    "An unexpected error occurred": "حدث خطأ غير متوقع",
    "An unexpected error occurred.": "حدث خطأ غير متوقع.",
    "Annual Leave": "إجازة سنوية",
    "Any additional comments (optional)": "أي تعليقات إضافية (اختياري)",
    "Applied Overrides": "التجاوزات المطبقة",
    "Archived": "مؤرشف",
    "Archived At": "مؤرشف في",
    "Archived snapshots for financial rights preservation": "لقطات مؤرشفة للحفاظ على الحقوق المالية",
    "Are you sure you want to": "هل أنت متأكد أنك تريد",
    "Are you sure you want to activate this employee?": "هل أنت متأكد أنك تريد تفعيل هذا الموظف؟",
    "Are you sure you want to add this salary transaction?": "هل أنت متأكد أنك تريد إضافة معاملة الراتب هذه؟",
    "Are you sure you want to assign the selected employees to this department?": "هل أنت متأكد أنك تريد تعيين الموظفين المحددين لهذا القسم؟",
    "Are you sure you want to assign this employee to this department?": "هل أنت متأكد أنك تريد تعيين هذا الموظف لهذا القسم؟",
    "Are you sure you want to cancel this request?": "هل أنت متأكد أنك تريد إلغاء هذا الطلب؟",
    "Are you sure you want to cancel this request? This action cannot be undone.": "هل أنت متأكد أنك تريد إلغاء هذا الطلب؟ لا يمكن التراجع عن هذا الإجراء.",
    "Are you sure you want to change your password?": "هل أنت متأكد أنك تريد تغيير كلمة المرور الخاصة بك؟",
    "Are you sure you want to check in now? Your check-in time will be recorded immediately.": "هل أنت متأكد أنك تريد تسجيل الدخول الآن؟ سيتم تسجيل وقت الدخول فوراً.",
    "Are you sure you want to check out now? Your check-out time will be recorded immediately.": "هل أنت متأكد أنك تريد تسجيل الخروج الآن؟ سيتم تسجيل وقت الخروج فوراً.",
    "Are you sure you want to create": "هل أنت متأكد أنك تريد إنشاء",
    "Are you sure you want to create this attendance record?": "هل أنت متأكد أنك تريد إنشاء سجل الحضور هذا؟",
    "Are you sure you want to create this employee?": "هل أنت متأكد أنك تريد إنشاء هذا الموظف؟",
    "Are you sure you want to create this project?": "هل أنت متأكد أنك تريد إنشاء هذا المشروع؟",
    "Are you sure you want to create this task?": "هل أنت متأكد أنك تريد إنشاء هذه المهمة؟",
    "Are you sure you want to deactivate this employee?": "هل أنت متأكد أنك تريد إلغاء تفعيل هذا الموظف؟",
    "Are you sure you want to delete": "هل أنت متأكد أنك تريد حذف",
    "Are you sure you want to delete of": "هل أنت متأكد أنك تريد حذف",
    "Are you sure you want to delete this Twitter account?": "هل أنت متأكد أنك تريد حذف حساب تويتر هذا؟",
    "Are you sure you want to delete this attendance record? This action cannot be undone.": "هل أنت متأكد أنك تريد حذف سجل الحضور هذا؟ لا يمكن التراجع عن هذا الإجراء.",
    "Are you sure you want to delete this department?": "هل أنت متأكد أنك تريد حذف هذا القسم؟",
    "Are you sure you want to delete this employee? This action cannot be undone.": "هل أنت متأكد أنك تريد حذف هذا الموظف؟ لا يمكن التراجع عن هذا الإجراء.",
    "Are you sure you want to delete this meeting?": "هل أنت متأكد أنك تريد حذف هذا الاجتماع؟",
    "Are you sure you want to delete this request?": "هل أنت متأكد أنك تريد حذف هذا الطلب؟",
    "Are you sure you want to delete this request? This action cannot be undone.": "هل أنت متأكد أنك تريد حذف هذا الطلب؟ لا يمكن التراجع عن هذا الإجراء.",
    "Are you sure you want to delete this salary transaction? This action cannot be undone.": "هل أنت متأكد أنك تريد حذف معاملة الراتب هذه؟ لا يمكن التراجع عن هذا الإجراء.",
    "Are you sure you want to delete this task?": "هل أنت متأكد أنك تريد حذف هذه المهمة؟",
    "Are you sure you want to save these details and activate this employee account?": "هل أنت متأكد أنك تريد حفظ هذه التفاصيل وتفعيل حساب الموظف؟",
    "Are you sure you want to submit this request?": "هل أنت متأكد أنك تريد إرسال هذا الطلب؟",
    "Are you sure you want to unassign this employee from their department?": "هل أنت متأكد أنك تريد إلغاء تعيين هذا الموظف من قسمه؟",
    "Are you sure you want to update": "هل أنت متأكد أنك تريد تحديث",
    "Are you sure you want to update organization details?": "هل أنت متأكد أنك تريد تحديث تفاصيل المؤسسة؟",
    "Are you sure you want to update this task?": "هل أنت متأكد أنك تريد تحديث هذه المهمة؟",
    "Are you sure you want to update your profile information?": "هل أنت متأكد أنك تريد تحديث معلومات ملفك الشخصي؟",
    "Ask a question...": "اكتب سؤالاً...",
    "Ask questions, check agenda templates, summarize points, or manage your company's tasks.": "اطرح الأسئلة، وتابع قوالب جداول الأعمال، ولخص النقاط، أو أدر مهام شركتك.",
    "Assign Department": "تعيين قسم",
    "Assign Department to Employees": "تعيين قسم للموظفين",
    "Assigned": "مُعيَّن",
    "Assigned - Due Date": "المُعيَّن - تاريخ الاستحقاق",
    "Assigned Employee(s)": "الموظف(ون) المُعيَّنون",
    "Assigned to": "مُعيَّن إلى",
    "Assignee": "المُعيَّن له",
    "Assignees": "المُعيَّن لهم",
    "Assigning...": "جارٍ التعيين...",
    "Assistant Logo": "شعار المساعد",
    "Attach": "إرفاق",
    "Attach file": "إرفاق ملف",
    "Attendance History": "سجل الحضور",
    "Attendance Record Deleted": "تم حذف سجل الحضور",
    "Attendance Time": "وقت الحضور",
    "Attendance created successfully": "تم إنشاء سجل الحضور بنجاح",
    "Attendance record deleted successfully": "تم حذف سجل الحضور بنجاح",
    "Attributes Keys": "مفاتيح السمات",
    "Auto (Average of employee performance)": "تلقائي (متوسط أداء الموظف)",
    "Auto (Average of internal stages)": "تلقائي (متوسط المراحل الداخلية)",
    "Auto (Average of internal tasks)": "تلقائي (متوسط المهام الداخلية)",
    "Auto (Based on calculations)": "تلقائي (بناءً على الحسابات)",
    "Automatic calculation": "حساب تلقائي",
    "Avatar": "الصورة الرمزية",
    "Avatar Preview:": "معاينة الصورة الرمزية:",
    "Back": "رجوع",
    "Back to Dashboard": "العودة إلى لوحة التحكم",
    "Back to Login": "العودة إلى تسجيل الدخول",
    "Back to my view": "العودة إلى صفحتي",
    "Balance After": "الرصيد بعد",
    "Billed recurringly": "فوترة متكررة",
    "Billing Information": "معلومات الفوترة",
    "Billing address": "عنوان الفوترة",
    "Binding Failure": "فشل الربط",
    "Binding Success": "نجاح الربط",
    "Blocked": "محظور",
    "Bonus": "مكافأة",
    "Bonus Amount": "قيمة المكافأة",
    "Bonuses": "المكافآت",
    "Brief description of the issue": "وصف مختصر للمشكلة",
    "Browse File": "تصفح الملف",
    "Buy Tokens": "شراء توكنز",
    "CSV File": "ملف CSV",
    "CVV": "CVV",
    "Callback URL": "رابط回调",
    "Cancel Meeting": "إلغاء الاجتماع",
    "Cancel Request": "إلغاء الطلب",
    "Cancel edit": "إلغاء التعديل",
    "Cancel subscription renewal": "إلغاء تجديد الاشتراك",
    "Cancelled": "ملغي",
    "Cancelling request...": "جارٍ إلغاء الطلب...",
    "Card": "بطاقة",
    "Card Expiry": "انتهاء صلاحية البطاقة",
    "Card Number": "رقم البطاقة",
    "Catalog Company": "شركة الكتالوج",
    "Category": "التصنيف",
    "Category created": "تم إنشاء التصنيف",
    "Category deleted (related accounts were also removed)": "تم حذف التصنيف (تمت إزالة الحسابات المرتبطة أيضاً)",
    "Category is required": "التصنيف مطلوب",
    "Category updated": "تم تحديث التصنيف",
    "Change Billing Info": "تغيير معلومات الفوترة",
    "Change Department": "تغيير القسم",
    "Change Plan": "تغيير الخطة",
    "Change Status": "تغيير الحالة",
    "Change password": "تغيير كلمة المرور",
    "Chat": "المحادثة",
    "Chat Details": "تفاصيل المحادثة",
    "Chat Group Title": "عنوان المجموعة",
    "Chat History": "سجل المحادثة",
    "Chat Permissions": "صلاحيات المحادثة",
    "Chat history": "سجل المحادثة",
    "Chat icon": "أيقونة المحادثة",
}

# Fill in empty keys
filled = 0
for k in ar:
    if ar[k] == "" and k in translations:
        ar[k] = translations[k]
        filled += 1

json.dump(ar, open('public/locales/ar/translation.json', 'w', encoding='utf-8'), ensure_ascii=False, indent=2)

import shutil
shutil.copy2('public/locales/ar/translation.json', 'public/locale/ar/translation.json')

print(f"Filled {filled} Arabic translations")
print(f"Still empty: {len([k for k,v in ar.items() if v == ''])}")
