import {Almarai} from "next/font/google";
import "./globals.css";

import React from "react";
import Providers from "./providers";
import {store} from "@/redux/store";
import {Provider} from "react-redux";


export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const almarai = Almarai({subsets: ["arabic"], weight: ["300", "400", "700", "800"], display: "swap"});

export default function RootLayout({children}) {
    return (
        <html lang="en">
        <body className={almarai.className}>
        <Providers> {children}</Providers>
        </body>
        </html>
    );
}
