import { Almarai } from "next/font/google";
import dynamic from "next/dynamic";
import "./globals.css";
import PropTypes from "prop-types";

// Lazy-load Providers so layout.js stays small (avoids ChunkLoadError timeouts during dev recompiles)
const Providers = dynamic(() => import("./providers"), {
    loading: () => null,
});
export const metadata = {
    title: "Create Next App",
    description: "Generated by create next app",
};

const almarai = Almarai({ subsets: ["arabic"], weight: ["300", "400", "700", "800"], display: "swap" });

export default function RootLayout({ children }) {
    return (
        <html lang="en" suppressHydrationWarning>
            <body className={almarai.className} suppressHydrationWarning>
                <Providers> {children}</Providers>
            </body>
        </html>
    );
}

RootLayout.propTypes = {
    children: PropTypes.node.isRequired,
}